module.exports.WAIT_BETWEEN_FAILED_LOGINS = 60000;
module.exports.LOGIN_ATTEMPTS_WITHOUT_WAIT = 3;
module.exports.BCRYPT_SALT = 10;
module.exports.JWT_ACCESS_TOKEN_EXPIRATION = '15m'
module.exports.JWT_REFRESH_TOKEN_EXPIRATION_SECONDS = 1*24*60*60
 